title: I'm Linkan.
author: GitHub User
email: linkan469@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an good description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: https://twitter.com/MajumderLinkan
github_username:  https://github.com/LinkanMajumder

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

